// @license
// Copyright (c) Audanika
//
// Use of this source code is governed by terms that can be
// found in the LICENSE file in the root of this package.

// ignore_for_file: type=lint, unused_field, unused_element

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: unused_import, unused_element, deprecated_member_use_from_same_package
@ffi.DefaultAsset(
  'package:aud_midi_apple/src/native/aud_midi_apple_bindings.g.dart',
)
library;

import 'dart:ffi' as ffi;
import 'package:objective_c/objective_c.dart' as objc;

const _$objcVersionCheck = objc.ObjCVersionCheck(9, 6);
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>()
external void CFRelease(ffi.Pointer<ffi.Void> cf);

@ffi.Native<
  ffi.Pointer<objc.CFString> Function(
    ffi.Pointer<__CFAllocator>,
    ffi.Pointer<ffi.UnsignedShort>,
    ffi.Long,
  )
>()
external ffi.Pointer<objc.CFString> CFStringCreateWithCharacters(
  ffi.Pointer<__CFAllocator> alloc,
  ffi.Pointer<ffi.UnsignedShort> chars,
  int numChars,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<objc.CFString>,
    CFRange,
    ffi.Pointer<ffi.UnsignedShort>,
  )
>(isLeaf: true)
external void CFStringGetCharacters(
  ffi.Pointer<objc.CFString> theString,
  CFRange range,
  ffi.Pointer<ffi.UnsignedShort> buffer,
);

@ffi.Native<ffi.Long Function(ffi.Pointer<objc.CFString>)>(isLeaf: true)
external int CFStringGetLength(ffi.Pointer<objc.CFString> theString);

/// Returns one of a given device's entities.
@ffi.Native<ffi.UnsignedInt Function(ffi.UnsignedInt, ffi.UnsignedLong)>()
external int MIDIDeviceGetEntity(int device, int entityIndex0);

/// Returns the number of entities in a given device.
@ffi.Native<ffi.UnsignedLong Function(ffi.UnsignedInt)>()
external int MIDIDeviceGetNumberOfEntities(int device);

/// Disposes a virtual source or destination your client created.
@ffi.Native<ffi.Int Function(ffi.UnsignedInt)>()
external int MIDIEndpointDispose(int endpt);

/// Returns an endpoint's entity.
@ffi.Native<ffi.Int Function(ffi.UnsignedInt, ffi.Pointer<ffi.UnsignedInt>)>()
external int MIDIEndpointGetEntity(
  int inEndpoint,
  ffi.Pointer<ffi.UnsignedInt> outEntity,
);

/// Returns one of a given entity's destinations.
@ffi.Native<ffi.UnsignedInt Function(ffi.UnsignedInt, ffi.UnsignedLong)>()
external int MIDIEntityGetDestination(int entity, int destIndex0);

/// Returns an entity's device.
@ffi.Native<ffi.Int Function(ffi.UnsignedInt, ffi.Pointer<ffi.UnsignedInt>)>()
external int MIDIEntityGetDevice(
  int inEntity,
  ffi.Pointer<ffi.UnsignedInt> outDevice,
);

/// Returns the number of destinations in a given entity.
@ffi.Native<ffi.UnsignedLong Function(ffi.UnsignedInt)>()
external int MIDIEntityGetNumberOfDestinations(int entity);

/// Returns the number of sources in a given entity.
@ffi.Native<ffi.UnsignedLong Function(ffi.UnsignedInt)>()
external int MIDIEntityGetNumberOfSources(int entity);

/// Returns one of a given entity's sources.
@ffi.Native<ffi.UnsignedInt Function(ffi.UnsignedInt, ffi.UnsignedLong)>()
external int MIDIEntityGetSource(int entity, int sourceIndex0);

/// Unschedules previously-sent packets.
@ffi.Native<ffi.Int Function(ffi.UnsignedInt)>()
external int MIDIFlushOutput(int dest);

/// Returns one of the destinations in the system.
@ffi.Native<ffi.UnsignedInt Function(ffi.UnsignedLong)>()
external int MIDIGetDestination(int destIndex0);

/// Returns one of the devices in the system.
@ffi.Native<ffi.UnsignedInt Function(ffi.UnsignedLong)>()
external int MIDIGetDevice(int deviceIndex0);

/// Returns the number of destinations in the system.
@ffi.Native<ffi.UnsignedLong Function()>()
external int MIDIGetNumberOfDestinations();

/// Returns the number of devices in the system.
@ffi.Native<ffi.UnsignedLong Function()>()
external int MIDIGetNumberOfDevices();

/// Returns the number of sources in the system.
@ffi.Native<ffi.UnsignedLong Function()>()
external int MIDIGetNumberOfSources();

/// Returns one of the sources in the system.
@ffi.Native<ffi.UnsignedInt Function(ffi.UnsignedLong)>()
external int MIDIGetSource(int sourceIndex0);

/// Locates a device, external device, entity, or endpoint by its uniqueID.
@ffi.Native<
  ffi.Int Function(ffi.Int, ffi.Pointer<ffi.UnsignedInt>, ffi.Pointer<ffi.Int>)
>()
external int MIDIObjectFindByUniqueID(
  int inUniqueID,
  ffi.Pointer<ffi.UnsignedInt> outObject,
  ffi.Pointer<ffi.Int> outObjectType,
);

/// Gets an object's integer-type property.
@ffi.Native<
  ffi.Int Function(
    ffi.UnsignedInt,
    ffi.Pointer<objc.CFString>,
    ffi.Pointer<ffi.Int>,
  )
>()
external int MIDIObjectGetIntegerProperty(
  int obj,
  ffi.Pointer<objc.CFString> propertyID,
  ffi.Pointer<ffi.Int> outValue,
);

/// Gets an object's string-type property.
@ffi.Native<
  ffi.Int Function(
    ffi.UnsignedInt,
    ffi.Pointer<objc.CFString>,
    ffi.Pointer<ffi.Pointer<objc.CFString>>,
  )
>()
external int MIDIObjectGetStringProperty(
  int obj,
  ffi.Pointer<objc.CFString> propertyID,
  ffi.Pointer<ffi.Pointer<objc.CFString>> str,
);

/// Sets an object's integer-type property.
@ffi.Native<
  ffi.Int Function(ffi.UnsignedInt, ffi.Pointer<objc.CFString>, ffi.Int)
>()
external int MIDIObjectSetIntegerProperty(
  int obj,
  ffi.Pointer<objc.CFString> propertyID,
  int value,
);

/// Sets an object's string-type property.
@ffi.Native<
  ffi.Int Function(
    ffi.UnsignedInt,
    ffi.Pointer<objc.CFString>,
    ffi.Pointer<objc.CFString>,
  )
>()
external int MIDIObjectSetStringProperty(
  int obj,
  ffi.Pointer<objc.CFString> propertyID,
  ffi.Pointer<objc.CFString> str,
);

/// Establishes a connection from a source to a client's input port.
@ffi.Native<
  ffi.Int Function(ffi.UnsignedInt, ffi.UnsignedInt, ffi.Pointer<ffi.Void>)
>()
external int MIDIPortConnectSource(
  int port,
  int source,
  ffi.Pointer<ffi.Void> connRefCon,
);

/// Closes a previously-established source-to-input port connection.
@ffi.Native<ffi.Int Function(ffi.UnsignedInt, ffi.UnsignedInt)>()
external int MIDIPortDisconnectSource(int port, int source);

/// Creates a virtual source in a client.
@ffi.Native<
  ffi.Int Function(
    ffi.UnsignedInt,
    ffi.Pointer<objc.CFString>,
    ffi.Int,
    ffi.Pointer<ffi.UnsignedInt>,
  )
>()
external int MIDISourceCreateWithProtocol(
  int client,
  ffi.Pointer<objc.CFString> name,
  int protocol,
  ffi.Pointer<ffi.UnsignedInt> outSrc,
);

/// Calls MIDIBluetoothDriverActivateAllConnections; returns its OSStatus, or
/// AUD_MIDI_APPLE_UNSUPPORTED_ERROR before macOS 13 and iOS 16.
@ffi.Native<ffi.Int32 Function()>()
external int aud_midi_apple_bluetooth_activate_all();

/// Returns 1 when the Bluetooth MIDI driver functions exist (macOS 13, iOS
/// 16), else 0.
@ffi.Native<ffi.Int32 Function()>()
external int aud_midi_apple_bluetooth_available();

/// Calls MIDIBluetoothDriverDisconnect for the CoreBluetooth peripheral
/// [uuid] (UTF-8); returns its OSStatus, or AUD_MIDI_APPLE_UNSUPPORTED_ERROR
/// before macOS 13 and iOS 16.
@ffi.Native<ffi.Int32 Function(ffi.Pointer<ffi.Char>)>()
external int aud_midi_apple_bluetooth_disconnect(ffi.Pointer<ffi.Char> uuid);

/// Browses the local network for services of [type] (e.g. "_apple-midi._udp")
/// and resolves each to host and port; [callback] runs on a private queue.
/// Returns 0 and stores the browser in [out_browser], or a DNS-SD error.
@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<ffi.Char>,
    AudMidiAppleBrowseCallback,
    ffi.Pointer<ffi.Pointer<AudMidiAppleBrowser>>,
  )
>()
external int aud_midi_apple_browse_start(
  ffi.Pointer<ffi.Char> type,
  AudMidiAppleBrowseCallback callback,
  ffi.Pointer<ffi.Pointer<AudMidiAppleBrowser>> out_browser,
);

/// Stops [browser]; no callback runs after it returns.
@ffi.Native<ffi.Void Function(ffi.Pointer<AudMidiAppleBrowser>)>()
external void aud_midi_apple_browse_stop(
  ffi.Pointer<AudMidiAppleBrowser> browser,
);

/// Marks [client] closed and waits up to [timeout_ms] milliseconds until no
/// callback is in flight. Afterwards no callback touches the ring buffer or
/// calls the signal any more. Returns 0, or AUD_MIDI_APPLE_TIMEOUT_ERROR.
@ffi.Native<ffi.Int32 Function(ffi.Pointer<AudMidiAppleClient>, ffi.Int32)>()
external int aud_midi_apple_client_close(
  ffi.Pointer<AudMidiAppleClient> client,
  int timeout_ms,
);

/// Creates a MIDI client named [name] (UTF-8) on the shim's run loop thread
/// with one MIDI 1.0 input port, one MIDI 2.0 input port, one output port and
/// a ring buffer of [capacity_words] words (rounded up to a power of two).
/// [signal] is called whenever new data waits.
@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<ffi.Char>,
    AudMidiAppleSignal,
    ffi.Uint32,
    ffi.Pointer<ffi.Pointer<AudMidiAppleClient>>,
  )
>()
external int aud_midi_apple_client_create(
  ffi.Pointer<ffi.Char> name,
  AudMidiAppleSignal signal,
  int capacity_words,
  ffi.Pointer<ffi.Pointer<AudMidiAppleClient>> out_client,
);

/// Closes [client] if needed, disposes its ports and the MIDI client and
/// frees its memory. Endpoints created with the client are disposed by
/// CoreMIDI together with it.
@ffi.Native<ffi.Void Function(ffi.Pointer<AudMidiAppleClient>)>()
external void aud_midi_apple_client_dispose(
  ffi.Pointer<AudMidiAppleClient> client,
);

/// Returns the MIDIClientRef of [client].
@ffi.Native<ffi.Uint32 Function(ffi.Pointer<AudMidiAppleClient>)>()
external int aud_midi_apple_client_ref(ffi.Pointer<AudMidiAppleClient> client);

/// Creates a virtual destination named [name] (UTF-8) with [protocol] whose
/// packets enter the ring buffer of [client] with [ref_con]. Returns 0 and
/// stores the endpoint in [out_destination], or an OSStatus;
/// AUD_MIDI_APPLE_PARAM_ERROR for a protocol other than 1 and 2.
@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<AudMidiAppleClient>,
    ffi.Pointer<ffi.Char>,
    ffi.Int32,
    ffi.Uint32,
    ffi.Pointer<ffi.Uint32>,
  )
>()
external int aud_midi_apple_destination_create(
  ffi.Pointer<AudMidiAppleClient> client,
  ffi.Pointer<ffi.Char> name,
  int protocol,
  int ref_con,
  ffi.Pointer<ffi.Uint32> out_destination,
);

/// Returns the input port of [client] for [protocol] (1 = MIDI 1.0, 2 = MIDI
/// 2.0), or 0 for another protocol.
@ffi.Native<ffi.Uint32 Function(ffi.Pointer<AudMidiAppleClient>, ffi.Int32)>()
external int aud_midi_apple_input_port(
  ffi.Pointer<AudMidiAppleClient> client,
  int protocol,
);

/// Returns the current host time in mach ticks.
@ffi.Native<ffi.Uint64 Function()>(isLeaf: true)
external int aud_midi_apple_now();

/// Returns the output port of [client].
@ffi.Native<ffi.Uint32 Function(ffi.Pointer<AudMidiAppleClient>)>()
external int aud_midi_apple_output_port(ffi.Pointer<AudMidiAppleClient> client);

/// Returns kMIDIPropertyUMPActiveGroupBitmap (a CFStringRef), or NULL before
/// macOS 14 and iOS 17.
@ffi.Native<ffi.Pointer<ffi.Void> Function()>()
external ffi.Pointer<ffi.Void>
aud_midi_apple_property_ump_active_group_bitmap();

/// Returns kMIDIPropertyUMPCanTransmitGroupless (a CFStringRef), or NULL
/// before macOS 14 and iOS 17.
@ffi.Native<ffi.Pointer<ffi.Void> Function()>()
external ffi.Pointer<ffi.Void>
aud_midi_apple_property_ump_can_transmit_groupless();

/// Copies up to [capacity_records] notification records into [buffer] and
/// returns their number. Clears the pending notification signal first.
@ffi.Native<
  ffi.Uint32 Function(
    ffi.Pointer<AudMidiAppleClient>,
    ffi.Pointer<ffi.Uint32>,
    ffi.Uint32,
  )
>(isLeaf: true)
external int aud_midi_apple_read_notifications(
  ffi.Pointer<AudMidiAppleClient> client,
  ffi.Pointer<ffi.Uint32> buffer,
  int capacity_records,
);

/// Copies complete packet records into [buffer] (at most [capacity_words]
/// words) and returns the number of words copied; 0 when the ring buffer is
/// empty. Clears the pending packet signal first.
@ffi.Native<
  ffi.Uint32 Function(
    ffi.Pointer<AudMidiAppleClient>,
    ffi.Pointer<ffi.Uint32>,
    ffi.Uint32,
  )
>(isLeaf: true)
external int aud_midi_apple_read_packets(
  ffi.Pointer<AudMidiAppleClient> client,
  ffi.Pointer<ffi.Uint32> buffer,
  int capacity_words,
);

/// Distributes the UMP [words] from the virtual [source] with [timestamp]
/// (mach ticks; 0 means now) to the clients connected to it. Returns 0 or an
/// OSStatus.
@ffi.Native<
  ffi.Int32 Function(
    ffi.Uint32,
    ffi.Int32,
    ffi.Uint64,
    ffi.Pointer<ffi.Uint32>,
    ffi.Uint32,
  )
>()
external int aud_midi_apple_receive(
  int source,
  int protocol,
  int timestamp,
  ffi.Pointer<ffi.Uint32> words,
  int word_count,
);

/// Sends the UMP [words] through [port] to [destination] at [timestamp] (mach
/// ticks, 0 = now) in event lists of [protocol]. Returns 0 or an OSStatus;
/// AUD_MIDI_APPLE_PARAM_ERROR when the words end in the middle of a UMP or
/// for a protocol other than 1 and 2.
@ffi.Native<
  ffi.Int32 Function(
    ffi.Uint32,
    ffi.Uint32,
    ffi.Int32,
    ffi.Uint64,
    ffi.Pointer<ffi.Uint32>,
    ffi.Uint32,
  )
>()
external int aud_midi_apple_send(
  int port,
  int destination,
  int protocol,
  int timestamp,
  ffi.Pointer<ffi.Uint32> words,
  int word_count,
);

/// Registers the service [name] of [type] on [port] with the TXT record [txt]
/// ([txt_length] bytes) and waits up to [timeout_ms] for the registrar.
/// Returns 0, stores the service in [out_service] and the registered name,
/// which may differ after a conflict, in [out_name] ([name_capacity] bytes);
/// or returns a DNS-SD error.
@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Uint16,
    ffi.Pointer<ffi.Uint8>,
    ffi.Uint16,
    ffi.Int32,
    ffi.Pointer<ffi.Char>,
    ffi.Uint32,
    ffi.Pointer<ffi.Pointer<AudMidiAppleService>>,
  )
>()
external int aud_midi_apple_service_register(
  ffi.Pointer<ffi.Char> name,
  ffi.Pointer<ffi.Char> type,
  int port,
  ffi.Pointer<ffi.Uint8> txt,
  int txt_length,
  int timeout_ms,
  ffi.Pointer<ffi.Char> out_name,
  int name_capacity,
  ffi.Pointer<ffi.Pointer<AudMidiAppleService>> out_service,
);

/// Withdraws [service].
@ffi.Native<ffi.Void Function(ffi.Pointer<AudMidiAppleService>)>()
external void aud_midi_apple_service_unregister(
  ffi.Pointer<AudMidiAppleService> service,
);

/// Returns the number of packets dropped because the ring buffer was full
/// since the last call, and resets it.
@ffi.Native<ffi.Uint64 Function(ffi.Pointer<AudMidiAppleClient>)>(isLeaf: true)
external int aud_midi_apple_take_dropped(
  ffi.Pointer<AudMidiAppleClient> client,
);

/// Stores the numerator and the denominator that convert mach ticks to
/// nanoseconds.
@ffi.Native<
  ffi.Void Function(ffi.Pointer<ffi.Uint32>, ffi.Pointer<ffi.Uint32>)
>()
external void aud_midi_apple_timebase(
  ffi.Pointer<ffi.Uint32> numer,
  ffi.Pointer<ffi.Uint32> denom,
);

/// Returns the number of 32-bit words of the UMP that starts with [word].
@ffi.Native<ffi.Uint32 Function(ffi.Uint32)>(isLeaf: true)
external int aud_midi_apple_ump_size(int word);

@ffi.Native<ffi.Pointer<objc.CFString>>()
external ffi.Pointer<objc.CFString> kMIDIPropertyDisplayName;

@ffi.Native<ffi.Pointer<objc.CFString>>()
external ffi.Pointer<objc.CFString> kMIDIPropertyDriverOwner;

@ffi.Native<ffi.Pointer<objc.CFString>>()
external ffi.Pointer<objc.CFString> kMIDIPropertyManufacturer;

@ffi.Native<ffi.Pointer<objc.CFString>>()
external ffi.Pointer<objc.CFString> kMIDIPropertyModel;

@ffi.Native<ffi.Pointer<objc.CFString>>()
external ffi.Pointer<objc.CFString> kMIDIPropertyName;

@ffi.Native<ffi.Pointer<objc.CFString>>()
external ffi.Pointer<objc.CFString> kMIDIPropertyOffline;

@ffi.Native<ffi.Pointer<objc.CFString>>()
external ffi.Pointer<objc.CFString> kMIDIPropertyPrivate;

/// constant kMIDIPropertyProtocolID
@ffi.Native<ffi.Pointer<objc.CFString>>()
external ffi.Pointer<objc.CFString> kMIDIPropertyProtocolID;

@ffi.Native<ffi.Pointer<objc.CFString>>()
external ffi.Pointer<objc.CFString> kMIDIPropertyUniqueID;

const int AUD_MIDI_APPLE_BROWSE_ERROR = 3;

const int AUD_MIDI_APPLE_BROWSE_FOUND = 1;

const int AUD_MIDI_APPLE_BROWSE_LOST = 2;

const int AUD_MIDI_APPLE_MAX_LIST_BYTES = 65536;

const int AUD_MIDI_APPLE_NOTIFICATIONS_LOST = 0;

const int AUD_MIDI_APPLE_NOTIFICATION_WORDS = 6;

const int AUD_MIDI_APPLE_PARAM_ERROR = -50;

const int AUD_MIDI_APPLE_RECORD_HEADER_WORDS = 7;

const int AUD_MIDI_APPLE_SIGNAL_NOTIFICATIONS = 2;

const int AUD_MIDI_APPLE_SIGNAL_PACKETS = 1;

const int AUD_MIDI_APPLE_TIMEOUT_ERROR = -1;

const int AUD_MIDI_APPLE_UNSUPPORTED_ERROR = -4;

/// Receives browse events; [name] and [host] are malloc'ed (or NULL) and belong
/// to the receiver, which frees them with free().
typedef AudMidiAppleBrowseCallback =
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Int32 event,
          ffi.Pointer<ffi.Char> name,
          ffi.Pointer<ffi.Char> host,
          ffi.Int32 port,
        )
      >
    >;

/// A running DNS-SD browse.
final class AudMidiAppleBrowser extends ffi.Opaque {}

/// A MIDI client with its input ports, output port and ring buffer.
final class AudMidiAppleClient extends ffi.Opaque {}

/// A registered DNS-SD service.
final class AudMidiAppleService extends ffi.Opaque {}

/// Receives the signal bits of new data; called from CoreMIDI threads.
typedef AudMidiAppleSignal =
    ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Int32 signals)>>;

final class CFRange extends ffi.Struct {
  @ffi.Long()
  external int location;

  @ffi.Long()
  external int length;

  static ffi.Pointer<CFRange> $allocate(
    ffi.Allocator $allocator, {
    required int location,
    required int length,
  }) => $allocator<CFRange>()
    ..ref.location = location
    ..ref.length = length;
}

final class __CFAllocator extends ffi.Opaque {}
